apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: killa-root-ca
  namespace: cert-manager

spec:
  isCA: true
  commonName: Killa Platform Root CA

  subject:
    organizations:
      - Killa
    organizationalUnits:
      - Platform Engineering

  secretName: killa-root-ca

  dnsNames:
    - '*.apps.killa.io'
    - 'apps.killa.io'

  duration: 87600h
  renewBefore: 8760h

  privateKey:
    algorithm: ECDSA
    size: 384

  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io