---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ra
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-ra
  secretName: root-ra-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io